line-length = 120

[format]
quote-style = "double"

[lint]
preview = true
select = [
    "B",       # flake8-bugbear rules
    "C4",      # flake8-comprehensions
    "E",       # pycodestyle E rules
    "F",       # pyflakes rules
    "FURB",    # refurb rules
    "I",       # isort rules
    "N",       # pep8-naming
    "PT",      # flake8-pytest-style rules
    "PLC0208", # iteration-over-set
    "PLC2801", # unnecessary-dunder-call
    "PLC0414", # useless-import-alias
    "PLR0402", # manual-from-import
    "PLR1711", # useless-return
    "PLR1714", # repeated-equality-comparison
    "RUF013",  # implicit-optional
    "RUF019",  # unnecessary-key-check
    "RUF100",  # unused-noqa
    "RUF101",  # redirected-noqa
    "RUF200",  # invalid-pyproject-toml
    "S506",    # unsafe-yaml-load
    "SIM",     # flake8-simplify rules
    "TRY400",  # error-instead-of-exception
    "TRY401",  # verbose-log-message
    "UP",      # pyupgrade rules
    "W191",    # tab-indentation
    "W605",    # invalid-escape-sequence

    # Security related linting rules
    # https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    "S",

    # avoid shadowing builtins
    # https://docs.astral.sh/ruff/rules/#flake8-builtins-a
    "A",

    # prohibit calls to `breakpoint()` in committed code
    # https://docs.astral.sh/ruff/rules/#flake8-debugger-t10
    "T10",
]

ignore = [

    # ===================== flake8-bandit (S) rules =====================
    "S101", # use of assert detected, https://docs.astral.sh/ruff/rules/assert/
    # hardcoded-bind-all-interfaces, https://docs.astral.sh/ruff/rules/hardcoded-bind-all-interfaces/
    # disabled beacause of false positives
    "S104",
    # hardcoded-password-string, https://docs.astral.sh/ruff/rules/hardcoded-password-string/
    # disabled beacause of false positives
    "S105",

    "E402", # module-import-not-at-top-of-file
    "N815", # mixed-case-variable-in-class-scope
]


[lint.pyflakes]
extend-generics = ["_pytest.monkeypatch", "tests.integration_tests"]
